version: "3.8"
services:
  icecast:
    build:
      context: ./icecast-docker
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - ICECAST_SOURCE_PW=hackme 
  mpd:
    build:
      context: ./mpd-docker
      dockerfile: Dockerfile   
    environment:
      - STREAM_ENCODING=vorbis
      - STREAM_BITRATE=192
      - STREAM_MOUNT_POINT=mystream
    volumes:
      - ./music:/music/
  mpc:
    build:
      context: ./mpd-docker
      dockerfile: Dockerfile
    command: bash -c "mpc -h mpd update && mpc -h mpd ls | mpc -h mpd add && mpc -h mpd shuffle && mpc -h mpd play && echo 'Playing...'"
    depends_on:
      - icecast
      - mpd 
